# Config file for Rotom
# Google "YAML tutorial" if you don't know how it works
---
bot:
    token: YOUR_TOKEN

    # You only need it if you want to give owner access to other people than you
    # The bot will check your Discord app info and add you into the owner list
    owner: 
    - YOUR DISCORD ID

    prefix: 
    - ":"
    - "::"

    # Enter the name of the database if you want to use it, otherwise enter ~ instead
    db: ~
    
    # Choose to either parse bots' commands in their messages or not.
    allow_bot: no

    # Multiserver support
    region: [] # Empty for all regions
    #fallback: ~ # Fallback servers

# Check what cogs to load, by default all .py files in cogs/ folder will be loaded.
# Both blacklist and whitelist must be in either collection or list containing the cog name.
cogs:
    # If not ~, stops the bot from loading listed cog(s) when bot is initialized
    blacklist: ~
    # If not ~, make the bot load *only* the cog(s) listed when bot is initialized
    whitelist: ~
    # Otherwise, if you don't want the bot to autoload any cogs, use this option
    # This is also useful if you don't want to load any cogs at start for debugging etc. purpose
    autoload: yes

defaults:
    # Default rolename settings, ~ for none, capitalization DOESN'T matter, will not be used in selfbot mode
    superuser: Rotom superuser
    admin: Rotom admin

# Params to be passed to rotom.py's Bot class, DO NOT touch it unless you know what are you doing.
# http://discordpy.readthedocs.io/en/latest/api.html#discord.Client
# https://github.com/Rapptz/discord.py/blob/master/discord/ext/commands/bot.py#L146
params:
    self_bot: no