# Config file for Rotom
# Google "YAML tutorial" if you don't know how it works
---
bot:
    token: YOUR_TOKEN

    owner: 
    - YOUR DISCORD ID
    prefix: 
    - ":"
    - "::"

    init_status: ~ # Optional
    shard_num  : 1 # Do NOT change the value if you don't know what exactly is it

# If you don't know what is this section for, ignore it and make sure you have RethinkDB up and running
db:
    name   : rotom
    host   : localhost
    port   : 28015

    user   : ~
    passwd : ~

# Arguments to be passed to rotom.py's Bot class, DO NOT touch it unless you know what are you doing.
args:
    bot: True

# If you don't know what is this section for, ignore it too, this section is mainly for bot devs
api:
    # Put your API keys here to push server count to either sites
    # If you don't want to use it, set the value to "~"
    carbonitex: ~
    dbots     : ~
