# Config file for Rotom
# Google "YAML tutorial" if you don't know how it works
---
bot:
    token: YOUR_TOKEN
    prefix: 
    - ":"
    - "::"
    # Choose to either parse bots' commands in their messages or not.
    parse_bot_message: no

    # Check what cogs to load, by default all .py files in cogs/ folder will be loaded.
    # Both blacklist and whitelist must be in either collection or list containing the cog name.
    cogs:
        # If you don't want the bot to autoload any cogs, use this option
        # This is also useful if you don't want to load any cogs at start for debugging etc. purpose
        autoload: yes
        # ONLY EITHER WILL BE USED, they will be loaded in order, so e.g. if whitelist isn't empty it will be used instead.
        # NOTE: The lists won't block load cogs command from working.
        # If not ~, make the bot load *only* the cog(s) listed when bot is initialized
        only_allow: ~
        # If not ~, stops the bot from loading listed cog(s) when bot is initialized
        disallow: ~
    
    db:
        # Enabling database usage
        enabled: yes

        # If true, values below will be used.
        name: rotom
        host: localhost:5984


    defaults:
        # Default rolename settings, ~ for none, CASE-SENSITIVE.
        admin:
        - Rotom Admin
        mod:
        - Rotom Mod

    # Params to be passed to rotom.py's Bot class, DO NOT touch it unless you know what are you doing.
    # http://discordpy.readthedocs.io/en/rewrite/api.html#discord.Client
    # https://github.com/Rapptz/discord.py/blob/rewrite/discord/ext/commands/bot.py#L780
    params:
        self_bot: no

# Put cog settings below with cog file name as key