# Config file for Rotom
# Google "YAML tutorial" if you don't know how it works
---
bot:
    token: YOUR_TOKEN
    owner: 
    - YOUR DISCORD ID
    prefix: 
    - ":"
    - "::"

# If you don't know what is this section for, ignore it and make sure you have RethinkDB up and running
db:
    name   : rotom
    host   : localhost
    port   : 28015

    user   : ~
    passwd : ~

# Params to be passed to rotom.py's Bot class, DO NOT touch it unless you know what are you doing.
# http://discordpy.readthedocs.io/en/latest/api.html#discord.Client
# https://github.com/Rapptz/discord.py/blob/master/discord/ext/commands/bot.py#L146
params:
    bot: True

# If you don't know what is this section for, ignore it too, this section is mainly for bot devs
api:
    carbonitex : ~
    dbots      : ~
