# Config file for Rotom
---
token      : ~ # Replace ~ with your bot token, otherwise the bot won't run
prefix     : [":", "::"] # If you can't figure out how to add it, Google ""
init_status: ~ # Optional
shard_num  : 1 # Do NOT change the value if you don't know what exactly does it do

# If you don't know what is this section for, ignore it and
# make sure you installed CouchDB and have it up and running
db:
    name   : rotom
    host   : localhost
    port   : 5984

    wrapper: couchdb # Bot will automatically find db_<wrapper>.py in ext folder

# If you don't know what is this section for, ignore it too
# This section is mainly for bot devs and/or larger scale bots (250 or more servers)
api:
    # Put your API keys here to push server count to either sites
    # If you don't want to use it, set the value to "~"
    carbonitex: ~
    dbots     : ~

    # This section is mainly for music feature, also TBD if I'm going to use it
    youtube   :
    soundcloud:
