# Config file for Rotom
---
# Replace ~ with your bot token, otherwise the bot won't run
token      : ~
# Add owner(s)'s ID inside the array
owner      : - YOUR DISCORD ID
# If you can't figure out how to add it, Google "YAML collection example"
prefix     : - ":"
             - "::"

init_status: ~ # Optional
shard_num  : 1 # Do NOT change the value if you don't know what exactly does it do

# If you don't know what is this section for, ignore it and
# make sure you installed CouchDB and have it up and running
db:
    name   : rotom
    host   : localhost
    port   : 28015

    user   : ~
    passwd : ~

# If you don't know what is this section for, ignore it too
# This section is mainly for bot devs and/or larger scale bots (250 or more servers)
api:
    # Put your API keys here to push server count to either sites
    # If you don't want to use it, set the value to "~"
    carbonitex: ~
    dbots     : ~
